### ISSUE TITLE
Support Entangle version 0.7

### ISSUE THREAD

**Issue by ofrias** [manuq/stopmo_preview#4]
Currently this plugin does not support Entangle 0.7.2.  This is the error trace:

```
$ entangle 
/home/ofrias/.config/entangle/plugins/stopmo_preview/stopmo_preview.py:5: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/home/ofrias/.config/entangle/plugins/stopmo_preview/stopmo_preview.py:9: PyGIWarning: PeasGtk was imported without specifying a version first. Use gi.require_version('PeasGtk', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PeasGtk

(entangle:3785): libpeas-WARNING **: Error importing plugin 'stopmo_preview':
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/ofrias/.config/entangle/plugins/stopmo_preview/stopmo_preview.py", line 10, in <module>
    from gi.repository import Entangle
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Entangle, introspection typelib not found

(entangle:3785): libpeas-WARNING **: Error loading plugin 'stopmo_preview'
```

Could you please add support for version 0.7 ?   Thanks!

**Comment by ofrias** [comment]
Oops, that was my fault, the error was caused by a missing library.  To fix:

`sudo apt-get install gir1.2-entangle-0.1`

**Comment by brunetton** [comment]
This issue should probably be closed ?
